### ISSUE TITLE
SOmap

### ISSUE THREAD

**Issue by UlrikeBraeckman** [SCAR/EGABIcourse19#6]
Hi,

I'm trying to run the code in the 05_Overview.Rmd and 50_Mapping.Rmd scripts that use SOmap(), but get this error message:

Error: .onLoad failed in loadNamespace() for 'sf', details:
  call: get(genname, envir = envir)
  error: object 'group_map' not found

Somap() was installed from github. The sf package is installed. Loading it explicitly does not solve the problem either.

Any suggestions are welcome.

thanks, Ulrike

**Comment by UlrikeBraeckman** [comment]
Hi again,

Grant had a look at the issue. It's solved now, by reinstalling tidyverse and dplyr and loading sf again.

thanks :-)

Ulrike

**Comment by raymondben** [comment]
Hooray!
